spring:
  application:
    name: simulator
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres
    username: postgres.hbhwwpgikvnczrnitijg
    password: Khai@201005
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080
